### PR TITLE
HT-3210: progress tracker via prometheus / pushgateway

### PR DESCRIPTION
**Pull request by aelkiss**
- add ProgressTracker for use by cron jobs
- add pushgateway for docker-compose for development
- update google submodule to return metrics

### CODE REVIEW

**Comment by aelkiss** [comment]
FYI @daaang , @jsteverman 

Compare to https://github.com/hathitrust/holdings-backend/blob/main/lib/utils/push_metrics_waypoint.rb (which doesn't yet implement the 'stage' idea)

@moseshll  Do you think it's worth adding tests for this, and if so, what's your sense of what the best option for testing would be? For holdings, we didn't add unit tests for PushMetricsWaypoint (above), but some of the existing tests at least exercise the code, and we stub the request to prometheus using webmock. If we do test this, I'm not sure what the best option for doing that is - the most thorough would be to run the pushgateway image in docker, push actual metrics to it, and then test that they show up if we curl the pushgateway. A pure unit testing approach where we try to stub `Net::Prometheus` and individual metrics seems kind of fiddly. A middle ground might be to stub the LWP useragent and test that we're posting what we expect.

**Comment by moseshll** [comment]
If the pushgateway docker addition here is configured and working, I'd say use that as it's the closest fit between dev/test and IRL. I understand that's a big "if" at this point.

**Comment by aelkiss** [comment]
:+1: Yes, it is working (there isn't really any configuration needed for it.) I'll see if I can add a test for that.

**Comment by aelkiss** [comment]
Added tests.

In this case all the tests just look at the exposed metrics from the pushgateway.

We could probably change some of the tests to look at what gets pushed to the pushgateway (i.e. the output of `$self->{prom}->render`), but these tests are 1) fast enough as-is, 2) consistent, and 3) avoids confusion between what the internal state is vs. what's actually been pushed to the pushgateway.

@moseshll , @daaang : thoughts?

**Comment by aelkiss** [comment]
Some backup expiration tests are now failing, presumably because of using `Test::Time`. As in Ruby, the dependencies leak between tests... I'll take a look.

**Comment by aelkiss** [comment]
In inspecting I can't replicate the failure; I suspect it has to do with the vagary of randomness in the test setup; perhaps it happened to end up with two versions with the same timestamp. I'm going to try re-running the tests and see if it recurs. If so, there's probably some difference between the CI environment and my local one that I don't understand. If not, this is probably an issue with test setup, and we could perhaps consider either reducing the randomness in test setup or at least logging what that randomness was so we can reproduce.

**Comment by moseshll** [comment]
I also got the test failures and didn't pay much mind yesterday since it was a WIP. I'll have a look after lunch.

**Review by moseshll — APPROVED** [review]
Looks good. No errors here.

**Pull request merged**
