### PR TITLE
HT-3330: Support for testing FTPS in development

### PR DESCRIPTION
**Pull request by aelkiss**
- curl
- ftps server in docker-compose
- config for using ftps server

The curlrc automatically adds --insecure (-k) in development since we
only have a self-signed certificate.

### CODE REVIEW

**Comment by aelkiss** [comment]
FYI @niquerio -- maybe of interest for testing sending holdings to zephir

**Comment by aelkiss** [comment]
See also https://github.com/hathitrust/feed_jobs/pull/18

**Comment by aelkiss** [comment]
Looks like Zephir actually uses vsftpd, so I'll see if I can find a docker image for that & get that working with docker-compose with FTPS

**Comment by aelkiss** [comment]
I poked a bit at vsftpd, but I didn't find anything that seemed particularly well-maintained; I tried generating my own vsftpd config but ran into a bunch of yak-shaving. I think this is good enough for now, and if we find some incompatibility in the future we can do something different.

**Review by jsteverman — APPROVED** [review]

**Pull request merged**
