### PR TITLE
TTO-14 Remove digitizer check by default

### PR DESCRIPTION
**Pull request by aelkiss**
This was relying on hacks in several package types to determine the apparent digitizer, and it's better to check specifically what we can in each package type where it matters.

### CODE REVIEW

**Comment by aelkiss** [comment]
(To be clear: the only package type where we can determine anything about the digitizer with any reliability is Google, and there only Google vs. non-Google. It would be nice if we had a reliable way for material ingested via Internet Archive, since there can be library-uploaded material as well as IA-scanned material, but to date we haven't had a reliable way.)

**Review by moseshll — APPROVED** [review]
I also had problems running the tests (collate.t and storage_migrate.t, GitHub action has issues with queue.t) but I don't think my errors are related to these changes.

**Comment by aelkiss** [comment]
OK. Tests passed locally for me. I will try re-running in GHA and see if we get the same results.

**Comment by aelkiss** [comment]
My guess is some race condition/ordering issue with dependent services, but I don't know what specifically.

**Pull request merged**
